services:
  postgres:
    restart: unless-stopped
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web
  redis:
    restart: unless-stopped
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - web

volumes:
  postgres_data:
  redis_data: